### PR TITLE
Pet buff fixes and macro icon modification

### LINKED ISSUE #38: Ensure buffing warlock pets (pets in general) works
Hey, are you able to add support to buff warlock pets?

Need that extra minmax buff on the felguard with my motw :D

### PR DESCRIPTION
**Pull request by Anonomit**
Pet zone is no longer unknown (uses owner's zone). Pets are considered to be in the correct raid groups (used by Raid groups watch settings). These changes should fix #38. Previously pet buffing would not work at all if "Scan members in same zone" is enabled (pet zone was always nil), and it would not work in raids because pets were considered to be in group 9 (failed in src/TaskScan.lua line 429).
NOTE: I'm unsure if group 9 is used by any other logic, but if so then this may introduce unintended behaviour.

Re-added the DISABLED macro icon so there's a visual difference between these two states: "Unable to buff due to combat" and "unable to buff because there is nothing to do".
The question mark icon is only visible when there is something to do but combat is preventing it. Otherwise the icon will be the specific buff or the DISABLED icon (demo roar). I think this behaviour is an improvement because the (ugly) question mark icon is only seen when there's an actual issue: combat lockdown interrupting buffs. Of course the icon still cannot change from DISABLED to QUESTION_MARK in combat.

### CODE REVIEW

**Comment by Anonomit** [comment]
Just to make sure the intended behaviour for the macro icon is clear, here is the behaviour I'm proposing:
1. Ready to cast a buff - The macro shows the icon and tooltip of the buff.
2. Nobody needs buffs - The macro shows the DISABLED icon (demo roar).
3. Someone needs a buff but I'm in combat - The macro shows the question mark icon.

And this is the current behaviour:
1. Ready to cast a buff - The macro shows the icon and tooltip of the buff.
2. Nobody needs buffs - The macro shows the question mark icon.
3. Someone needs a buff but I'm in combat - The macro shows the question mark icon.

**Comment by kvakvs** [comment]
Question mark was suggested by another addon user, question mark is a special texture making the game show first castable spell in the macro which is nice.

**Comment by kvakvs** [comment]
I'll be testing and later commit separately the pet changes, thanks for that

I am not merging the icon changes. In fact i never look at the icon neither should anyone - bind it to a button and press it every time you see buffomat window pop up. The only way i can see that change go in, is via a checkbox in options, as opt-in.

**Comment by TimCowan** [comment]
I'm the one who originally suggested the question mark. The behaviour here is how I suggested it be implemented. I find the window is too big, so a macro icon is a very helpful feature to let me know the status of buffs.

**Comment by Anonomit** [comment]
I am the one who suggested the question mark icon. When you implemented it, you didn't make the changes as suggested. This PR "fixes" it to the intended behaviour.

**Comment by Anonomit** [comment]
As to your point about the macro icon, I find that the window is unnecessarily large, so I prefer to keep it hidden and look at the macro icon to see if any buffs are queued up.

**Comment by kvakvs** [comment]
For window size there's UI scale option in addon settings, make it very small no problem.

**Comment by Anonomit** [comment]
I have tried putting it at minimum size. It doesn't get as small as a spell icon. All I really want is a little indicator that tells me if any spells need to be cast, and the macro does that for me.

**Comment by kvakvs** [comment]
I'll make your change as a checkbox option. Is that good enough?

**Comment by Anonomit** [comment]
That's fine with me. Do you mean the option would change between the current and the proposed behviour? I don't understand why anyone would prefer the current, since it only adds ambiguity as outlined in my comment above https://github.com/kvakvs/BuffomatClassic/pull/74#issuecomment-1060235826

**Pull request merged**
